# 1. Cấu hình Server
server.port=8080

# 2. Kết nối Database SQLite
# Lưu ý: file .db sẽ được lưu trong folder 'database' ở thư mục gốc project
spring.datasource.url=jdbc:sqlite:database/information.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# 3. Cấu hình JPA / Hibernate
# Sử dụng Dialect cộng đồng cho SQLite (vì bạn đã thêm dependency này trong pom.xml)
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# 'update' giúp tự động tạo bảng dựa trên code Java (Entity) của bạn

spring.jpa.hibernate.ddl-auto=create

# Hiện câu lệnh SQL dưới console để bạn dễ debug lỗi

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Cấu hình cho phép H2 Console (Tùy chọn - nếu bạn muốn xem DB qua trình duyệt)
# Với SQLite, bạn thường dùng phần mềm DB Browser for SQLite để xem file .db thì tốt hơn.